### ISSUE TITLE
[BUG] CR-30 Z motor reversed

### ISSUE THREAD

**Issue by rmcolbert** [CR30-Users/Marlin-CR30#4]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Z motor direction on stock CR-30 motherboard should be inverted true. 2.0.9.1 has it set to false. It was true in the last 2.0.8.x release

### Bug Timeline

New w/ 2.0.9.1

### Expected behavior

Belt should move towards the front of the printer when moving + Z

### Actual behavior

Belt moves towards the back of the printer

### Steps to Reproduce

1. Auto-home
2. Move Z +100mm

### Version of Marlin Firmware

2.0.9.1

### Printer model

Creality CR-30

### Electronics

Stock

### Add-ons

none

**Comment by BrownRhined** [comment]
#define INVERT_Z_DIR true

**Comment by adelyser** [comment]
Closing as it was fixed with 3ded6c5b104bd5e93b19e031d435034708621fcf
